[database]

# Currently we only support sqlite3.
driver = "sqlite3"

# Set the path of the database.
name = "database.sqlite3"

[email]

# none, smtp
method = "none"

smtp_user = "yourusername"
smtp_port = 587
smtp_host = "smtp.google.com"
smtp_pass = "yourpassword"
